infer_cfgs:
  # DeepSpeed and VLLM configurations
  ds_cfgs: ds_z3_config.json
  vllm_cfgs: vllm_basic.json
  
default:
  # Evaluation configurations
  eval_cfgs:
    # Output directory name
    output_dir: null
    # Number of shots
    n_shot: 5
    # Chain of Thought
    cot: false

  # Configuration for data
  data_cfgs:
    # Task name(s)
    task: [hybridqa]
    # Task directory
    task_dir: hybridqa
    # Evaluation split (e.g., dev, test)
    split: dev

  # Model configurations
  model_cfgs:
    # Model identifier
    model_id: Meta-Llama-3-8B-Instruct
    # Pretrained model name or path
    model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
    # Chat template
    chat_template: Llama3
    # Maximum token length
    model_max_length: 2048
